version: '3.3'

services:
  database:
    image: postgres:14.2
    ports:
      - "0.0.0.0:5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: apidb

  adminer:
    image: adminer:4.8.1
    ports:
      - 8845:8080
    environment:
      ADMINER_DESIGN: lucas-sandery
      ADMINER_DEFAULT_SERVER: database
      ADMINER_DEFAULT_DB_DRIVER: pgsql

volumes:
  data: